import { z } from 'zod'
import { callToolApi } from '../lib/api-client.js'

export const annualReturnSchema = z.object({
  companyNumber: z.string().describe('Gibraltar company registration number'),
  companyName: z.string().describe('Full registered company name'),
  registeredOffice: z.string().describe('Full registered office address'),
  returnDateDay: z.string().describe('Annual return date day (e.g. "15")'),
  returnDateMonth: z.string().describe('Annual return date month (e.g. "March 2026")'),
  nominalShareCapital: z.string().optional(),
  totalShares: z.string().optional(),
  shareClass: z.string().optional(),
  nominalValuePerShare: z.string().optional(),
  sharesTakenUp: z.string().optional(),
  sharesIssuedForCash: z.string().optional(),
  sharesIssuedNotCash: z.string().optional(),
  sharesPartlyPaid: z.string().optional(),
  sharesAtDiscount: z.string().optional(),
  amountCalledPerShare: z.string().optional(),
  totalCallsReceived: z.string().optional(),
  callsUnpaid: z.string().optional(),
  totalIndebtedness: z.string().optional(),
  shareholder1Name: z.string().optional(),
  shareholder1Address: z.string().optional(),
  shareholder1Occupation: z.string().optional(),
  shareholder1Shares: z.string().optional(),
  shareholder2Name: z.string().optional(),
  shareholder2Address: z.string().optional(),
  shareholder2Occupation: z.string().optional(),
  shareholder2Shares: z.string().optional(),
  shareholder3Name: z.string().optional(),
  shareholder3Address: z.string().optional(),
  shareholder3Occupation: z.string().optional(),
  shareholder3Shares: z.string().optional(),
  shareholder4Name: z.string().optional(),
  shareholder4Address: z.string().optional(),
  shareholder4Occupation: z.string().optional(),
  shareholder4Shares: z.string().optional(),
  director1Name: z.string().optional(),
  director1FormerNames: z.string().optional(),
  director1Nationality: z.string().optional(),
  director1NationalityOfOrigin: z.string().optional(),
  director1Address: z.string().optional(),
  director1Occupation: z.string().optional(),
  director2Name: z.string().optional(),
  director2FormerNames: z.string().optional(),
  director2Nationality: z.string().optional(),
  director2NationalityOfOrigin: z.string().optional(),
  director2Address: z.string().optional(),
  director2Occupation: z.string().optional(),
  director3Name: z.string().optional(),
  director3FormerNames: z.string().optional(),
  director3Nationality: z.string().optional(),
  director3NationalityOfOrigin: z.string().optional(),
  director3Address: z.string().optional(),
  director3Occupation: z.string().optional(),
  director4Name: z.string().optional(),
  director4FormerNames: z.string().optional(),
  director4Nationality: z.string().optional(),
  director4NationalityOfOrigin: z.string().optional(),
  director4Address: z.string().optional(),
  director4Occupation: z.string().optional(),
  hasSecretary: z.string().optional(),
  secretaryName: z.string().optional(),
  secretaryFormerNames: z.string().optional(),
  secretaryNationality: z.string().optional(),
  secretaryNationalityOfOrigin: z.string().optional(),
  secretaryAddress: z.string().optional(),
  secretaryOccupation: z.string().optional(),
  sicCode: z.string().optional(),
  companySize: z.string().optional(),
  numberOfEmployees: z.string().optional(),
  financialYearEndDay: z.string().optional(),
  financialYearEndMonth: z.string().optional(),
  filedByName: z.string().optional(),
  filedByAddress: z.string().optional(),
  filedByEmail: z.string().optional(),
  signatoryName: z.string().optional(),
})

export async function handleAnnualReturn(args: z.infer<typeof annualReturnSchema>) {
  const result = await callToolApi('/api/tools/annual-return', args)
  if (result.type === 'binary') {
    return {
      content: [{
        type: 'text' as const,
        text: JSON.stringify({
          message: 'Annual return ZIP generated successfully',
          filename: result.filename,
          mimeType: result.mimeType,
          base64Data: result.base64Data,
        }),
      }],
    }
  }
  return { content: [{ type: 'text' as const, text: JSON.stringify(result.data, null, 2) }] }
}
